# Generated by Django 3.1.3 on 2020-11-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image_msg',
            field=models.ImageField(blank=True, null=True, upload_to='chats/messages'),
        ),
    ]
